"""
Django settings for pixelamproject project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-csc^_goygf)-&ri08tnrjqvw6idtf129=t2tqmbooiznipb@d%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['.vercel.app','127.0.0.1']  # Allow all hosts temporarily for testing purposes

CSRF_TRUSTED_ORIGINS = ['https://pixelam.vercel.app/']

# ALLOWED_HOSTS = ['*','.app']
# CSRF_TRUSTED_ORIGINS = ['.app']

# ALLOWED_HOSTS = ['d96d-103-97-227-5.ngrok-free.app']
# CSRF_TRUSTED_ORIGINS = ['https://d96d-103-97-227-5.ngrok-free.app']


# ALLOWED_HOSTS = ['5744-103-97-227-18.ngrok-free.app']
# CSRF_TRUSTED_ORIGINS = ['5744-103-97-227-18.ngrok-free.app']
# CSRF_TRUSTED_ORIGINS = ['https://5744-103-97-227-18.ngrok-free.app']
# https://d96d-103-97-227-5.ngrok-free.app/

# https://d96d-103-97-227-5.ngrok-free.app/
# Application definition

INSTALLED_APPS = [
    'pixelapp.apps.PixelappConfig',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pixelamproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pixelamproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'rBtJFxUegIhKIuiqWrivEuNjijwIvsUJ',
        'HOST': 'monorail.proxy.rlwy.net',
        'PORT': '14977',
    }
}

# Railway.app
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'railway',
#         'USER': 'postgres',
#         'PASSWORD': 'zwzNNUNFFwrmJsUkEfUVtyIRIRfolkzd',
#         'HOST': 'roundhouse.proxy.rlwy.net',
#         'PORT': '41385',
#     }
# }

# pyhtonanywhere.com
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'pawargta$pixelam',
#         'USER': 'pawargta',
#         'PASSWORD': 'mypixel@456',
#         'HOST': 'pawargta.mysql.pythonanywhere-services.com',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }


# mypixel@456


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT','DELETE']

import os
STATIC_MEDIA_URL = '/pixelapp/'
STATIC_MEDIA_ROOT = os.path.join(BASE_DIR, 'pixelapp')