# Generated by Django 4.2.2 on 2024-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
            ],
        ),
    ]
