# Generated by Django 4.2.2 on 2024-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('servicemode', models.CharField(max_length=200)),
                ('imgPath', models.CharField(max_length=300)),
                ('prompt', models.CharField(max_length=2000)),
                ('llmresp_imgPath', models.CharField(max_length=300)),
                ('llmresp_text', models.CharField(max_length=10000)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
