# Generated by Django 4.2.2 on 2024-05-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelapp', '0002_chatsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsdata',
            name='Fantellmresp_text',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='chatsdata',
            name='Kikuyullmresp_text',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='chatsdata',
            name='Kimerullmresp_text',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='chatsdata',
            name='Twillmresp_text',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='chatsdata',
            name='Yoruballmresp_text',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='chatsdata',
            name='llmresp_text',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='chatsdata',
            name='prompt',
            field=models.TextField(default='none'),
        ),
    ]
