# Generated by Django 4.2.2 on 2024-05-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelapp', '0006_chatsdata_image_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsdata',
            old_name='image_base64',
            new_name='botimage_base64',
        ),
        migrations.AddField(
            model_name='chatsdata',
            name='userimage_base64',
            field=models.TextField(default='none'),
        ),
    ]
